version: '3.1'

services:
  app:
    image: library_image:latest
    container_name: libraryapp
    ports:
      - "8080:8080"

    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: db_mysql

    ports:
      - "3600:3306"
    environment:
       MYSQL_ROOT_PASSWORD: 1234
       MYSQL_DATABASE: labs
       MYSQL_PASSWORD: qwerty
       MYSQL_USER: labs







