version: '3.8'
services:
  mysql:
    image: library/mysql:latest
    ports:
    - 3306:3306

  app:
    image: app
    ports:
      - target: 8080
        published: 8080
    depends_on:
      - mysql
    restart: on-failure
